/**
 * Roster → router config.json. The router's own config is fully generated:
 * everything in it is a consequence of the roster plus the library metadata,
 * so hand-edits would be overwritten and live only in the roster.
 */
import { PROVIDER_CONFIG_PATH, ENV_FILE, KIT_DIR, ROSTER_PATH, tilde } from "./paths.mjs";

export function renderRouterConfig(roster, resolved, registry, { port, localToken, library } = {}) {
  const routing = roster.routing ?? {};
  const cfg = {
    port: port ?? roster.router?.port ?? 8300,
    localToken: localToken ?? roster.router?.localToken ?? "local-auto-router",
    providerConfigPath: tilde(PROVIDER_CONFIG_PATH),
    typesafeEnvFile: tilde(ENV_FILE),
    // Where the roster and the kit CLI live, so the router's dashboard can
    // read the roster and run save-and-apply through the kit's own pipeline.
    kitRoot: tilde(KIT_DIR),
    rosterPath: tilde(ROSTER_PATH),
    typesafeModel: roster.typesafe?.model ?? "jev-1.13.0",
    judge: {
      mode: roster.judge?.mode ?? "typesafe",
      fastino: roster.judge?.fastino ?? null,
    },
    ttlHours: roster.typesafe?.ttlHours ?? routing.ttlHours ?? 6,
    routing: {
      wideChars: routing.wideChars ?? 1000000,
      minConfidence: routing.minConfidence ?? 0.6,
      workflowMinConfidence: routing.workflowMinConfidence ?? 0.4,
      omniModel: resolved.omniModel && { ...resolved.omniModel, candidates: resolved.omniChain ?? [resolved.omniModel] },
      wideModel: resolved.wideModel && { ...resolved.wideModel, candidates: resolved.wideChain ?? [resolved.wideModel] },
      workloads: Object.fromEntries(
        Object.entries(resolved.workloads).map(([name, t]) => [
          name,
          // candidates: the tier's whole usable chain, in roster preference
          // order — the raw material for the router's quota-aware steering.
          { ...t, candidates: resolved.chains?.[name] ?? [t] },
        ])
      ),
      defaultWorkload: resolved.defaultWorkload,
      // providerId → param dialect for the thinking policy ("thinking" |
      // "enable_thinking" | "reasoning_effort" | "none")
      thinkingStyles: roster.routing?.thinkingStyles ?? {},
      profiles: roster.profiles,
      mixture: {
        proposers: resolved.proposers,
        aggregator: resolved.aggregator,
        proposerTimeoutMs: roster.mixture.proposerTimeoutMs ?? 240000,
      },
      workflows: registry,
    },
  };
  const extraUpstreams = {};
  for (const [id, p] of Object.entries(roster.providers)) {
    if (p.routerOnly) extraUpstreams[id] = { baseUrl: p.baseUrl.replace(/\/+$/, ""), apiKeyEnv: p.apiKeyEnv };
  }
  if (Object.keys(extraUpstreams).length) cfg.extraUpstreams = extraUpstreams;
  // The full delegation library for the dashboard's registry editor — catalog
  // metadata only. The judge reads routing.workflows; this key is inert for
  // routing and exists so the UI can see every workflow, registered or not.
  if (library?.length) cfg.workflowLibrary = library;
  return cfg;
}

export function renderEnvHeader(roster, resolved) {
  const names = new Set();
  if (roster.typesafe?.apiKeyEnv) names.add(roster.typesafe.apiKeyEnv);
  for (const p of Object.values(roster.providers)) if (p.apiKeyEnv) names.add(p.apiKeyEnv);
  return [
    "Router runtime secrets — chmod 600, never committed, never in the roster.",
    "One KEY=value per line; values with spaces get quoted.",
    `Generated by zcode-router-kit from the roster (${resolved.envMissing.length ? `still missing: ${resolved.envMissing.join(", ")}` : "all referenced keys present"}).`,
  ];
}
