/**
 * Roster → router config.json. The router's own config is fully generated:
 * everything in it is a consequence of the roster plus the library metadata,
 * so hand-edits would be overwritten and live only in the roster.
 */
import { PROVIDER_CONFIG_PATH, ENV_FILE, tilde } from "./paths.mjs";

export function renderRouterConfig(roster, resolved, registry, { port, localToken } = {}) {
  const routing = roster.routing ?? {};
  const cfg = {
    port: port ?? roster.router?.port ?? 8300,
    localToken: localToken ?? roster.router?.localToken ?? "local-auto-router",
    providerConfigPath: tilde(PROVIDER_CONFIG_PATH),
    typesafeEnvFile: tilde(ENV_FILE),
    typesafeModel: roster.typesafe?.model ?? "jev-1.13.0",
    ttlHours: roster.typesafe?.ttlHours ?? routing.ttlHours ?? 6,
    routing: {
      wideChars: routing.wideChars ?? 1000000,
      minConfidence: routing.minConfidence ?? 0.6,
      workflowMinConfidence: routing.workflowMinConfidence ?? 0.4,
      omniModel: resolved.omniModel,
      wideModel: resolved.wideModel,
      workloads: resolved.workloads,
      defaultWorkload: resolved.defaultWorkload,
      profiles: roster.profiles,
      mixture: {
        proposers: resolved.proposers,
        aggregator: resolved.aggregator,
        proposerTimeoutMs: roster.mixture.proposerTimeoutMs ?? 240000,
      },
      workflows: registry,
    },
  };
  const extraUpstreams = {};
  for (const [id, p] of Object.entries(roster.providers)) {
    if (p.routerOnly) extraUpstreams[id] = { baseUrl: p.baseUrl.replace(/\/+$/, ""), apiKeyEnv: p.apiKeyEnv };
  }
  if (Object.keys(extraUpstreams).length) cfg.extraUpstreams = extraUpstreams;
  return cfg;
}

export function renderEnvHeader(roster, resolved) {
  const names = new Set();
  if (roster.typesafe?.apiKeyEnv) names.add(roster.typesafe.apiKeyEnv);
  for (const p of Object.values(roster.providers)) if (p.apiKeyEnv) names.add(p.apiKeyEnv);
  return [
    "Router runtime secrets — chmod 600, never committed, never in the roster.",
    "One KEY=value per line; values with spaces get quoted.",
    `Generated by zcode-router-kit from the roster (${resolved.envMissing.length ? `still missing: ${resolved.envMissing.join(", ")}` : "all referenced keys present"}).`,
  ];
}
